name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications:
    path: ../
  flutter_isolate: ^1.0.0+14

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  e2e: ^0.2.4+2
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - icons/

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
